# Generated by Django 4.2.2 on 2023-06-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=255, verbose_name='마니또 타입')),
                ('price', models.PositiveIntegerField(verbose_name='선물 금액')),
                ('mail_data', models.TextField(verbose_name='참가자 메일')),
                ('name_data', models.TextField(verbose_name='참가자 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날')),
                ('end_at', models.DateTimeField(null=True, verbose_name='마감날')),
            ],
            options={
                'verbose_name': 'Manito',
                'db_table': 'manito',
            },
        ),
    ]
