# Generated by Django 4.2.2 on 2023-06-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manito', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manito',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='마니또 만든 이'),
        ),
    ]
