# Generated by Django 4.2.2 on 2023-06-28 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manito_sender', models.CharField(max_length=255, verbose_name='보내는 사람')),
                ('manito_receiver', models.CharField(max_length=255, verbose_name='받는 사람')),
                ('manito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manito.manito', verbose_name='마니또')),
            ],
            options={
                'verbose_name': 'Partner',
                'db_table': 'partner',
            },
        ),
    ]
