# Generated by Django 4.2.2 on 2023-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='manito_receiver',
            field=models.CharField(max_length=255, verbose_name='받는 사람'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='manito_sender',
            field=models.CharField(max_length=255, verbose_name='보내는 사람'),
        ),
    ]
