# Generated by Django 4.2.2 on 2023-06-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manito', '0003_alter_manito_author'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='manito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manito.manito', verbose_name='마니또 제목'),
        ),
    ]
